### ISSUE TITLE
大佬，web界面安装之后没有创建后台页面啊

### ISSUE THREAD

**Issue by X-yhy** [broken5/Shots#4]
![Snipaste_2020-05-07_14-27-46](https://user-images.githubusercontent.com/31311038/81261607-f20d9480-906e-11ea-841f-2d3fe6e7b6ae.png)

**Comment by broken5** [comment]
没有显示的话去web目录public里面看看
项目今天要更新了，也可以待会更新完了，下载最新的

**Comment by X-yhy** [comment]
也没有，刚我下了最新的，成功显示了生成的后台文件了，但是提示让我登录，找不到登录界面。。。。 我还是一会等最新的吧

**Comment by broken5** [comment]
加我QQ2336490031



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yhy"<notifications@github.com&gt;; 
发送时间: 2020年5月7日(星期四) 下午3:00
收件人: "broken5/Shots"<Shots@noreply.github.com&gt;; 
抄送: "Broken_5"<2336490031@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [broken5/Shots] 大佬，web界面安装之后没有创建后台页面啊 (#4)





 
也没有，刚我下了最新的，成功显示了生成的后台文件了，但是提示让我登录，找不到登录界面。。。。 我还是一会等最新的吧
